version: '3'
services:
  payload:
    container_name: payload
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    expose:
      - "3000"
    env_file:
      - .env
    # ports:
    #   - "3000:3000"
    # command: ["yarn", "web", "start"]
    
    restart: unless-stopped